const PDFDocument = require('pdfkit');
const { Op } = require('sequelize');
const {
  Sale,
  SaleItem,
  Product,
  Customer,
  User,
  StoreSettings,
} = require('../models');

const generateDailyPDF = async (req, res, next) => {
  try {
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    const tomorrow = new Date(today);
    tomorrow.setDate(tomorrow.getDate() + 1);

    const sales = await Sale.findAll({
      where: { createdAt: { [Op.gte]: today, [Op.lt]: tomorrow } },
      include: [
        { model: SaleItem, as: 'items', include: [{ model: Product, as: 'product' }] },
        { model: Customer, as: 'customer' },
        { model: User, as: 'cashier', attributes: ['name'] },
      ],
      order: [['createdAt', 'ASC']],
    });

    const settings = await StoreSettings.findOne();
    const storeName = settings?.storeName || 'Smart Kirana';

    const doc = new PDFDocument({ margin: 50 });
    const dateStr = today.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=daily-report-${dateStr.replace(/ /g, '-')}.pdf`);
    doc.pipe(res);

    doc.fontSize(22).fillColor('#1B4332').text(storeName, { align: 'center' });
    doc.moveDown(0.5);
    doc.fontSize(14).fillColor('#1E293B').text('Daily Sales Report', { align: 'center' });
    doc.fontSize(10).text(dateStr, { align: 'center' });
    doc.moveDown(1.5);

    const totalRevenue = sales.reduce((s, sale) => s + parseFloat(sale.totalAmount), 0);
    const cashSales = sales.filter((s) => s.paymentMethod === 'cash').reduce((s, sale) => s + parseFloat(sale.totalAmount), 0);
    const creditSales = sales.filter((s) => s.paymentMethod === 'credit').reduce((s, sale) => s + parseFloat(sale.totalAmount), 0);

    doc.fontSize(11).text(`Total Transactions: ${sales.length}`);
    doc.text(`Total Revenue: PKR ${totalRevenue.toLocaleString()}`);
    doc.text(`Cash Sales: PKR ${cashSales.toLocaleString()}`);
    doc.text(`Credit Sales: PKR ${creditSales.toLocaleString()}`);
    doc.moveDown(1);

    doc.fontSize(12).fillColor('#1B4332').text('Transaction Details');
    doc.moveDown(0.5);

    sales.forEach((sale, idx) => {
      doc.fontSize(10).fillColor('#1E293B');
      doc.text(`${idx + 1}. ${sale.invoiceNumber} — PKR ${parseFloat(sale.totalAmount).toLocaleString()} (${sale.paymentMethod})`);
      doc.fontSize(9).fillColor('#64748B');
      doc.text(`   Cashier: ${sale.cashier?.name || 'N/A'} | Customer: ${sale.customer?.name || 'Walk-in'}`);
      sale.items.forEach((item) => {
        doc.text(`   • ${item.product?.name} x${item.quantity} = PKR ${parseFloat(item.subtotal).toLocaleString()}`);
      });
      doc.moveDown(0.3);
    });

    doc.moveDown(1);
    doc.fontSize(10).fillColor('#64748B').text('Generated by Smart Kirana MIS', { align: 'center' });

    doc.end();
  } catch (error) {
    next(error);
  }
};

const generateSalePDF = async (req, res, next) => {
  try {
    const sale = await Sale.findByPk(req.params.id, {
      include: [
        { model: SaleItem, as: 'items', include: [{ model: Product, as: 'product' }] },
        { model: Customer, as: 'customer' },
        { model: User, as: 'cashier', attributes: ['name'] },
      ],
    });

    if (!sale) {
      return res.status(404).json({ message: 'Sale not found' });
    }

    const settings = await StoreSettings.findOne();
    const storeName = settings?.storeName || 'Smart Kirana';

    const doc = new PDFDocument({ margin: 50, size: 'A5' });
    const dateStr = new Date(sale.createdAt).toLocaleDateString('en-GB', {
      day: '2-digit', month: 'short', year: 'numeric',
    });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=invoice-${sale.invoiceNumber}.pdf`);
    doc.pipe(res);

    doc.fontSize(18).fillColor('#1B4332').text(storeName, { align: 'center' });
    doc.moveDown(0.3);
    doc.fontSize(12).fillColor('#1E293B').text('INVOICE', { align: 'center' });
    doc.moveDown(0.5);

    doc.fontSize(9).text(`Invoice: ${sale.invoiceNumber}`);
    doc.text(`Date: ${dateStr}`);
    doc.text(`Cashier: ${sale.cashier?.name || 'N/A'}`);
    doc.text(`Customer: ${sale.customer?.name || 'Walk-in Customer'}`);
    doc.moveDown(0.5);

    doc.fontSize(9).fillColor('#1B4332');
    doc.text('Product                    Qty    Price      Subtotal');
    doc.moveDown(0.2);
    doc.fillColor('#1E293B');

    sale.items.forEach((item) => {
      const name = (item.product?.name || 'Item').substring(0, 22).padEnd(22);
      const qty = String(item.quantity).padStart(5);
      const price = `PKR ${parseFloat(item.unitPrice).toLocaleString()}`.padStart(10);
      const sub = `PKR ${parseFloat(item.subtotal).toLocaleString()}`.padStart(12);
      doc.text(`${name} ${qty} ${price} ${sub}`);
    });

    doc.moveDown(0.5);
    if (parseFloat(sale.discount) > 0) {
      doc.text(`Discount: PKR ${parseFloat(sale.discount).toLocaleString()}`, { align: 'right' });
    }
    doc.fontSize(12).fillColor('#1B4332').text(`TOTAL: PKR ${parseFloat(sale.totalAmount).toLocaleString()}`, { align: 'right' });
    doc.moveDown(0.3);
    doc.fontSize(9).fillColor('#1E293B').text(`Payment: ${sale.paymentMethod.toUpperCase()}`, { align: 'right' });

    doc.moveDown(1.5);
    doc.fontSize(10).fillColor('#64748B').text('Thank you for shopping!', { align: 'center' });

    doc.end();
  } catch (error) {
    next(error);
  }
};

module.exports = { generateDailyPDF, generateSalePDF };
